# Environment Oracle Free
# Prof. Taciano Balardin
version: '3.8'
services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    environment:
     - ORACLE_PASSWORD=123456
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/ORCL
volumes:
  oracle-data: